name: Render References by Pillar
on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install bibtexparser requests

      - name: Check links
        run: python scripts/link_check.py

      - name: Group BibTeX by Pillar
        run: python scripts/group_by_pillar.py

      - name: Convert Markdown → HTML
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
          # full page
          pandoc docs/_tmp_references.md -s -o references.html \
                --metadata title="Crew-Bidding References by Pillar" \
                --css style.css
          # mapping: Pillar → pretty slug
          declare -A SLUGS=(
            [T1]="T1-Foundations-and-Regulatory-Context"
            [T2]="T2-Algorithmic-Advances"
            [T3]="T3-Systems-and-Operational-Implementations"
            [T4]="T4-Data-and-Benchmark-Resources"
            [T5]="T5-Survey-and-Synthesis"
            [T6]="T6-AI-and-Data-Driven-Methods"
            [T7]="T7-Extensions-and-Inter-Domain-Innovations"
            [T8]="T8-Emerging-Frontiers"
          )
          for P in "${!SLUGS[@]}"; do
            MD="docs/_tmp_${P}.md"
            if [ -f "$MD" ]; then
              pandoc "$MD" -s -o "${P}.html" \
                    --metadata title="Crew-Bidding References — ${P}" \
                    --css style.css
              cp "${P}.html" "${SLUGS[$P]}.html"   # pretty URL
            fi
          done
          cp references.html index.html           # ← keeps root URL optional


      - name: Commit artefact
        run: |
          git config --global user.email "ci@agileaerosystems.com"
          git config --global user.name  "AA-CI Bot"
          git add *.html                 # ← stage references.html + T1.html … T8.html
          git diff --cached --quiet || \
            git commit -m "chore: auto-render refs [skip ci]"
          git push

